### ISSUE TITLE
Remote debugging not working on Intellij Idea

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#155]
_From [maurizio...@alfresco.com](https://code.google.com/u/112978353022216972888/) on November 07, 2013 06:52:04_

What steps will reproduce the problem? 
1. Generate AMP archetype (using 1.0.2)
2. export MAVEN_OPTS="-Xdebug -Xrunjdwp:server=y, transport=dt_socket,address=4000, suspend=y"
3. Open DemoComponentTest and add a breakpoint on line 63
4. mvn install -Pamp-to-war -Dmaven.surefire.debug
5. Step over line 64 What is the expected output? What do you see instead? Expected: Remote debugging sessions keeps on going
Current: net.sf.acegisecurity.providers.ProviderNotFoundException: No authentication provider for net.sf.acegisecurity.providers.UsernamePasswordAuthenticationToken

_Original issue: http://code.google.com/p/maven-alfresco-archetypes/issues/detail?id=155_

**Comment by montgolfiere** [comment]
Just an FYI, I also hit this issue when debugging Alfresco platform using Intellij IDEA. Thanks to @marcobiscaro2112 marcobiscaro2112 for the suggested workaround.

**Comment by andreuandon** [comment]
Why is this bug closed if we can still replicate the issue?

**Comment by ahmedowian** [comment]
@andreuandon, I guess since the workaround of unchecking Enable 'toString()' object view does work, the bug was deemed not worth fixing.  I can attest that this workaround works, as I also ran into this issue and tried out the workaround.   Thanks to @marcobiscaro2112.  
You could also just put your break point after the Alfresco service call, as @mindthegab mentioned.

**Comment by dhrn** [comment]
the solution is still working
