### ISSUE TITLE
SDK 2.0.0-SNAPSHOT doesn't work when running aggregator project with enterprise versione 4.1.7

### ISSUE THREAD

**Issue by pierchiodo** [Alfresco/alfresco-sdk#198]
When running aggregator project with packaging=pom and alfresco.version=4.1.7:  

[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-sdk-requirements) @ cattolica-alfresco-parent ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireProperty failed with message:
Property "alfresco.version" evaluates to "4.1.7".  This does not match the regular expression "^5..*"

**Comment by ikaygorodov** [comment]
Hi everyone, is there any new regarding the ticket?
Can Alfresco Maven SDK 2.1.x be used to build 4.2.x now?

(I can see that in the enforcer plugin configuration the build is limited to 5.x version, but is there other hurdles left?)

**Comment by ohej** [comment]
I never got around to picking up the SDK 1.2.x branch.

SDK 2.x is **not** compatible with Alfresco 4.2.x. This is mainly because of changes in the way Alfresco is packaged up in 4.2 vs 5.0. 

The main pain points is the way Solr is packaged and configured and JDK7 vs JDK8. The difference Solr packaging and configuration makes it impossible to reuse the profiles between 4.2 and 5.x.

Essentially this means that we manually have to merge changes between the two branches and maintain them which will end up being painful.

As we've progressed with SDK 2.x the gap between 4.2 and 5.x (and now 5.1) is getting wider, and I'm not sure it's the best approach to continue this.

We are working on a set of requirements for SDK 3.x which takes a completely new approach to things where we move more stuff into the alfresco-maven-plugin. This could simplify the process of having a unified SDK that **potentially** supports all the way from 4.2 to 5.1, but I can't stress enough that we do not know if 4.2 support will be a priority.

**Comment by ohej** [comment]
Unfortunately there is no sensible way to support 4.1. The amount of hacks we had to do to support 4.2 in SDK3 was in-depth. SDK3 does support 4.2 all the way up to 5.2, so I will close this issue.
