### ISSUE TITLE
Spring-Loaded does not seem to update the JSP classloader when methods are added/removed from classes

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-sdk#206]
I updated the sample .jsp to create a new instance of Demo and call init() on it. That worked without restarting things. Then I added a method to Demo and the jsp was not able to call the new method (it couldn't see the method.) However if I called the same method from init() it was clearly working.

It is possible that jhipster's extended version of spring loaded may help with this as well as other spring specific plugins. 

https://github.com/jhipster/jhipster-loaded

**Comment by jgoldhammer** [comment]
Heavy modification of JSPs are no longer a practice for alfresco development. I will close the issue for now because spring-reloaded is not supported in new alfresco sdk 3 version. @binduwavell , if you think we should take care, please reopen this issue with more information about your motivation.

Thanks
Jens
