### ISSUE TITLE
Share pages are not reloaded unless cache is explictly cleared

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#248]
In order to have Share pages hot reloaded we are currently using the surf development mode.

In the SDK 2.0.0 release candidate (against alfresco 5.0.c) pages are not reloaded unless caches are explicitly cleared with a 

POST /share/page/caches/dependency/clear

This is a known issue and looking at the [upstream depended issue](https://issues.alfresco.com/jira/browse/ACE-2566?focusedCommentId=336598&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-336598) we need to introduce a new ```<disable-resource-caching>true</disable-resource-caching>``` parameter in ```share-config-custom.xml```.

**Comment by ohej** [comment]
I have raised a few JIRA issues to address the overall state of hot reloading in Share:
https://issues.alfresco.com/jira/browse/ALF-21242
https://issues.alfresco.com/jira/browse/ALF-21243
https://issues.alfresco.com/jira/browse/ALF-21244
https://issues.alfresco.com/jira/browse/ALF-21245

It seems overall that the fix for ACE-2566 needs to be revisited and a proper solution is needed, which should fix the hot reloading issues with JS, CSS and i18n.

**Comment by mindthegab** [comment]
This is resolved in 2.1.0 (major new feature, webscripts are reloaded by the SDK). I shall re-generate the release notes at https://artifacts.alfresco.com/nexus/content/repositories/alfresco-docs/alfresco-sdk-aggregator/latest/github-report.html
