### ISSUE TITLE
Enable JS / CSS minification for Share-AMP

### ISSUE THREAD

**Issue by marcomancuso** [Alfresco/alfresco-sdk#269]
The Alfresco SDK 2.0 is not minifying JS/CSS
A customer is asking to add the ability to do it.
At the moment it's possible to do it just adding in the share-amp pom.xml the following.

```xml
<build>
  <plugins>
     <plugin>
	<!--There seems to be a bug in this plugin, that resources cannot be overriden ! So be careful what you minify -->
         <groupId>net.alchim31.maven</groupId>
	 <artifactId>yuicompressor-maven-plugin</artifactId>
	 <version>1.2</version>
	 <executions>
	     <execution>
		<id>compress-js</id>
		<goals>
		    <goal>compress</goal>
		</goals>
	    </execution>
	 </executions>
	<configuration>
	    <excludes>
		<exclude>alfresco/**/*.*</exclude>
		<exclude>**/*-min.js</exclude>
		<exclude>**/*.css</exclude>
	    </excludes>
	    <resources />
	    </configuration>
	</plugin>
   </plugins>
</build>
```
This should be already present in the SDK.

**Comment by marcomancuso** [comment]
Jira issue: https://issues.alfresco.com/jira/browse/MNT-13717

**Comment by gravitonian** [comment]
This is now in the code, but you need to build locally until we have done a new release

**Comment by mindthegab** [comment]
@gravitonian So the right processing for this issue needs to be:

1. Be assigned to someone so we have accountability (just assigned to you)
2. Be coded, committed and tested (assuming you have done that, but next time please add the issue #269 key in the commit comment so the commit will appear in this thread)
3. Be assigned to a milestone  so that once we release, release notes are automatically generated (just assigned
4. Be closed (I am doing this now), otherwise it lingers there and we can't easily evaluate progress

If post release still doesn't work, please reopen.
