### ISSUE TITLE
Recent change to master makes repo and share refresh run too agressively (for me :) )

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-sdk#283]
If I go into repo-amp and "mvn compile" (even without the refresh-repo profile) it attempts to refresh-repo (kinda cool even though I didn't specify the refresh-repo profile or goal, but also I don't always want that.) More importantly it attempts to refresh-share, which is definitely not what I want. Previously we had to explicitly use profiles to trigger refreshing, then that was changed so that we had to specify the alfresco:refresh* goals... now they are just magically running.

From reading through the alfresco-sdk-parent pom I see that the refresh-repo and refresh-share profiles are enabled based on the existence of src/main/amp/module.properties. These profiles then enable the refresh-repo and refresh-share goals respectively.

At the very least maybe we should change the refresh-share profile to enable when share-config-custom.xml.sample or share-config-custom.xml exist under src/main/resources/META-INF? Or some other share specific thing like the existence of the src/main/amp/config/alfresco/web-extension exits...

Also, I couldn't figure out how to specify refreshHost/refreshPort/etc via the mvn command line. I tried tons of stuff including -DrefreshHost=asdf -Drefresh-repo.refreshHost=fdsa... I thought this was working with 2.0.1-SNAPSHOT a while back, but maybe my memory is failing me...

FWIW, the following command can be used to disable the profiles which trigger the goals:

mvn compile -P-refresh-share,-refresh-repo

Worst case I can work with this, but it seems odd to me to have to disable share refreshing when I'm compiling a repo amp (or vica versa.)

While we are on this topic. It appears that we can't specify different ports for alfresco and share (which may matter for AIO if we get to the point where we can start alfresco and share containers independently -- I think there is a story about this somewhere...) Presumably we can reconfigure the plugin in repo-amp and/or share-amp to resolve this, seems kind of janky.

**Comment by ohej** [comment]
I've reworked this during the weekend and today, and I think we're close to something that satisfies everything. 

I've refactored a lot of the code in the Refresh Mojo's and introduced a new Mojo called "Refresh". This mojo has a property ``maven.alfresco.refreshMode`` which can be set to ``auto`` (default), ``both``, ``share``, ``repo`` and ``none``. 

Auto-mode checks if it's running against an AMP, if so it will check app.amp.client.war.artifactId and determine if it should refresh repo or share. If it's not an AMP it will refresh both repo and share.
 The property ``maven.alfresco.refreshMode`` can be set via command line or pom.

I've removed the refresh-share and refresh-repo profiles and introduced a new single profile "refresh-both" (I'll come up with a better name). This is enabled if src/main/amp/module.properties exists. 

This means that if you run "mvn compile" from the root of a AIO project it will build all the modules, once it reaches the repo module, it will check and figure out it's an Alfresco AMP and refresh web scripts for repo. The same thing happens when it reaches a Share AMP. 

This behaviour works great with Eclipse - it will automatically figure out which module you changed and refresh/clear dependency cache, and if the users don't want this they can always set ``maven.alfresco.refreshMode`` to ``none``

Now, the only downside to this is that if you have multiple AMPs and you run ``mvn compile`` from the commandline it will refresh for every AMP. I have not found any way around this, but I have set the ``alfresco:refresh`` goal to be an aggregator - this way if you run ``mvn alfresco:refresh`` it will (in auto mode) refresh both repo, share and skip all other modules.

Only trick left is IDEA. Since it doesn't invoke Maven when running "Make project" there is no way to detect which module was changed, and we're left with in limbo. It's easy to tell IDEA to run a goal after "Make project", so maybe the solution is just to make a goal that simply refreshes both, no matter what. That would enable new users to get started quickly, and once they get to know the details they have full flexiblity on the setup.

I'd appreciate some input on this :)

**Comment by ohej** [comment]
As for IDEA, I've added this to the parent pom for AIO:
````
<plugin>
  <groupId>org.alfresco.maven.plugin</groupId>
  <artifactId>alfresco-maven-plugin</artifactId>
</plugin>
````
This way the plugin shows up in IDEA and it's easy to set the refresh goal to be executed after make. With the default behaviour (refreshMode set to auto) it will detect that it's not an AMP and refresh both repo and share. This way new developers have a great chance for getting started quickly and experienced developers have full flexibility and control.

**Comment by ohej** [comment]
I also forgot to mention that port is not defaulting to the value of ``maven.tomcat.port``, and you can now override it.

**Comment by binduwavell** [comment]
So this logic will only occur for modules that explicitly include the alfresco-maven-plugin?

If so, I like the idea of having the plugin on amps modules and the AIO top level project.

I don't quite understand how aggregator mode works. If multiple repo amps cause repo refreshing, only one will trigger?

**Comment by ohej** [comment]
The logic will be triggered if ``src/main/amp/module.properties`` exists, this means if you run ``mvn compile`` from the root of an AIO project it will refresh web scripts/clear dependency cache on all modules that has a the file. 

If you run ``mvn compile`` in ``my-aio-project/share-amp`` it will refresh web scripts in Share and clear the dependency cache.

If you run ``mvn compile`` in ``my-aio-project/repo-amp`` it will refresh web scripts for repo.

If you run ``mvn compile`` in ``my-aio-project/repo`` it will not do anything :)

If you invoke ``mvn alfresco:refresh`` it will not build, compile, process-resources or anything else, it will only refresh web scripts and clear dependency cache. This is handy for people who are using IDE's which doesn't really invoke maven when building (IntelliJ IDEA..).

**Comment by binduwavell** [comment]
[5/11/15, 8:52:43 AM] Rufus "Bindu" Wavell: Ole, as far as I can tell from command line and from eclipse the refresh stuff is working great!
[5/11/15, 8:53:20 AM] Rufus "Bindu" Wavell: Having said that, I don't have an SDK project with multiple repo and/or share AMPs to test with. We have a couple but they are on 2.0.0 SDK and as others own them I'm not that comfortable using them for testing.
[5/11/15, 8:54:09 AM] Rufus "Bindu" Wavell: Refreshing is surprisingly fast
[5/11/15, 8:54:40 AM] Rufus "Bindu" Wavell: Thanks guys for spending time on this, I hope it will make a big difference to folks using the SDK.

**Comment by ohej** [comment]
Excellent, I'll close the issue then.
