### ISSUE TITLE
Add support for executing (integration testing) repo and share modules independently.

### ISSUE THREAD

**Issue by bhagyas** [Alfresco/alfresco-sdk#290]
Also referred at : #260

**Comment by ohej** [comment]
You can already do this by invoking tests on each AMP/module?
``cd repo-amp && mvn integration-test``

**Comment by mindthegab** [comment]
Can you please elaborate on the problem (not on the solution you think it's the best for your particular use case)?

Especially in spite of the extensive explanation from @ohej in issue #260, here https://github.com/Alfresco/alfresco-sdk/issues/260#issuecomment-109897119

Can you ask you to edit the description with something meaningful, explaining what you are trying to achieve, and which version of Alfresco (and SDK) does not allow you to do that and if possible why?

Otherwise we'll likely close this issue soon.

**Comment by jgoldhammer** [comment]
Copied @ohej answer from #260:

With all the effort of hot reloading going into the SDK we are hoping All-in-one will be the default adoption for developers. With the 2.1.0 release, we're in a much better shape than we were in 2.0.

With that being said, we do recognise that hot reloading is not perfect and you still have to bounce the server from time to time.

You have two options:

Use the AMP archetypes, have one for repo, one for share and run them separately. The Share AMP archetype is by default configured to run on port 8081
Split all-in-one up into two projects. One with repo, repo-amp, runner and solr-config, one with share, share-amp and runner. Change the ports and you're good to go
Remember that the archetypes are suggestions on what your project layout could look like. If the AMP archetypes doesn't cover your needs and you need to run Repo and Share in separate instances, then split all-in-one up.

For all-in-one to support this natively we'd have to look into forking the processes which we'd rather not do for now. The focus right now is to get hot reloading to a state where the restarts are not even needed at all.

I have raised https://issues.alfresco.com/jira/browse/DEVPLAT-105 to get the process into the official docs and closing the issue.
