### ISSUE TITLE
Do not force the use of the parent pom

### ISSUE THREAD

**Issue by slanglois** [Alfresco/alfresco-sdk#332]
I think that mandating the use of the `alfresco-sdk-parent` in projects who need to create or apply AMPs is a _bad_ idea. That parent pom can remain as a facility if it makes life simpler for some, but it should not be mandatory -- and I think not even encouraged.

Here is why!
1. It is definitely not standard - in my 10 years using Maven, I've never used a plugin that forced or even edvised the use of a specific parent pom. Ole found an exception with Spring Roo, but this is a very "constrained" framework to build applications. Alfresco is meant to be more open. 
2. separation of concerns: behaviours should be in the plugin, and configurations in the pom. By defining plugin executions in the parent pom (such as `add-module-properties-to-test-classpath`), you break this paradigm. 
3. In a multimodule build, I have one module that build an AMP, and 20 others that build JARs, WARs, etc. I don't want to change the parent pom of the whole project just for that one module
4. If 2 plugin providers impose that, I cannot use them both in the same build! (For instance: how do you create a Spring Roo application that also creates an AMP? There's only one parent POM)
5. Some companies mandate the use of their corporate parent pom, and you can't use another one.

So, I think we should move as many things as possible from the parent pom to the alfresco-maven-plugin, and if possible get rid of the parent pom altogether.

**Comment by rgauss** [comment]
+1

**Comment by alexmiller422** [comment]
+1

**Comment by lutzhorn** [comment]
+1

**Comment by ohej** [comment]
With my current experiments, a lot of things will be simplified a great deal, mainly by switching to JARs as the standard packaging (still with an option to do AMP as an assembly), the only thing we need from a parent pom would be default properties. So to make a project that creates a JAR that is deployable in Alfresco is really, really simple.

The trouble begins when we want to launch the embedded Tomcat with H2 and Solr. Here we need to configure the Tomcat plugin and do some custom stuff like replacing a few things on the `solr-config.zip` artifact. Without the parent pom, there's no way to share plugin configuration, which means the archetypes would have to contain all the logic for the runner.

This by itself could be just fine, but this means that if we change this config, we need to provide developers with troublesome upgrade instructions for updating to a new release of the SDK. This is why the parent pom was introduced in the first place. Granted, now that we have JARs and a lot of the artifacts are much nicer to work with, it's much cleaner and simpler but it is still a good chunk of code.

I can see us moving some of this stuff into the plugin, I'd love to have a `mvn alfresco:run` goal, but then we would have to wrap the embedded Tomcat inside our own Mojo, which ultimately could result in some messy code, since we'll basically have to wrap the `tomcat-maven-plugin`.

Another option could be for the JAR to simply be pure and clean, and add another module for running, which would then inherit from the SDK. The runner module would not produce any artifacts, only setup all the plumbing for Tomcat, H2, Solr etc.

Again, it's still early, if you have suggestions or ideas please come forward.

**Comment by mindthegab** [comment]
This requirement is a direct child of the AMP being a non standard extension and introducing unnecessary complexity at Dev time. 

We introduced a parent pom in the SDK because otherwise generated archetype poms would be cluttered and very confusing (validated feedback) for *novice maven developers*, which 3 years ago were the majority approaching Alfresco.

Clearly all of you are *advanced developers* and understand deeply maven and can live with a large amount of configuration in order to gain flexibility.

I am all in to remove the parent pom as we now (with 5.1) should have a much simpler logic in the SDK, back to maven standards. Talking about standard and best practices, in fact, there's little point in satisfying requirements 1-5 when we are imposing much more non standard things like:

1 - a non standard packaging format (AMP)
2 - non standard directory layout 

Said that, since 1 and 2 might just go in the new SDK version, totally happy to tackle this issue. 

Thanks for your feedback!

**Comment by jgoldhammer** [comment]
@ohej:
I think, we are on a good way with the current state. 
Do you think we can close the ticket? Or is there anything left?

Thanks
Jens

**Comment by ohej** [comment]
I am happy to say that SDK3 does no longer require a parent pom! Closing
