### ISSUE TITLE
Would be good to add a way to test the content models in an project using maven

### ISSUE THREAD

**Issue by rmknightstar** [Alfresco/alfresco-sdk#339]
Here is a sample of a shell implementation of this

```
for i in $ALF_HOME/tomcat/webapps/alfresco/WEB-INF/lib/*.jar
do
CLASSPATH=$CLASSPATH:$i
done
CLASSPATH=$CLASSPATH:$ALF_HOME/tomcat/webapps/alfresco/WEB-INF/lib/:$ALF_HOME/tomcat/webapps/alfresco/WEB-INF/classes/
export CLASSPATH
java org.alfresco.repo.dictionary.TestModel $*
```

This runs TestModel on all of the models in the Module before firing up a full blown repository

**Comment by lutzhorn** [comment]
How do you gather all model filenames into `$*`?

**Comment by tom-vandepoele** [comment]
You could also create a simple JUnit test class which matches the source of the org.alfresco.repo.dictionary.TestModel class. (You can't call that class directly in a JUnit test since it has System.exit calls coded in, which prevent you from seeing usable output directly, but simply duplicating the class and putting in your own asserts does the trick quite nicely)

You could then either run it manually or as part of maven's automated testing. (This doesn't need a repo running, so can go in the regular JUnit test phase, this isn't an integration test)

Just make sure you've included all models that you are referencing.
