### ISSUE TITLE
Audit configuration loaded multiple times when running embedded runner

### ISSUE THREAD

**Issue by bhagyas** [Alfresco/alfresco-sdk#340]
Startup throws errors.

The audit configurations are loaded from three places.
- amp/config/
- test-classes/
- WEB-INF

Throws the following exception multiple times.

```
org.alfresco.repo.audit.model.AuditModelException: 09290000 Audit application key 'auditkey' is used by: AuditApplication[ name=auditkey, id=2, disabledPathsId=3]
```

**Comment by ohej** [comment]
Just to be clear for reference: The audit config is loaded and works just fine, but since it is picked up from multiple locations it gives this error when starting.

The resulting AMP is fine and the error only happens when running with embedded tomcat. 

The only resolution for this is to avoid having files in multiple locations - ideally they should only be in the output directory. This is something we hope to fix with 3.x

**Comment by binduwavell** [comment]
Quick note that we just ran into this issue. Glad it was reported here which stops us spending too much time trying to figure out how to resolve the issue (I was gonna try and add a filtering exclusion somewhere, but agree a more general approach would be better.) So this is a rather long winded +1 ;)

**Comment by ohej** [comment]
With SDK 3 this issue has now gone away. Classes and beans are only loaded once. SDK2 did a copy of all resources into `target/test-classes` ensuring that all beans were actually loaded twice during start up.
