### ISSUE TITLE
Alfresco SDK repo projects do not allow to integrate other amp modules

### ISSUE THREAD

**Issue by jgoldhammer** [Alfresco/alfresco-sdk#348]
At the moment it is not possible to integrate other amp modules into an sdk repo project.
There was a workaround for former projects, but currently I have to copy jar files and config files separately.

see https://twitter.com/jensWR/status/667678469464137732

Can you please find a similar solution like amp overlays in all-in-one-projects?

**Comment by douglascrp** [comment]
Hey @jgoldhammer 

What I always do in these cases is to create 2 AIO based projects, one for repository customizations and the other for share customizations.
The next thing I do is to remove everything not needed on each project (repo, repo-runner and solr-config from the share project and share and share-runner from the repository project).
After that, it's required to remove the references into the submodules to reflect the changes I made.
Other thing I do is to rename the share-amp and repo-amp projects to something different, like <customer>-repo-amp and <customer>-share-amp, because if I use the default name, I could have problems if I install 2 or more AIO based projects, which would generate amps with the same file name.

After all of this, I'm thinking, why not using this structure as the base for alfresco and share archetypes?
Is there anything "special" on the current archetypes that I don't know about?

**Comment by binduwavell** [comment]
Jens, it's not all that hard to do this manually. We (at Zia) have been working on an open source Yeoman generator that will be able to assist with this. Although we aren't quite there, we do have some docs on the process. https://github.com/binduwavell/generator-alfresco/blob/master/incomplete-amp/AMP%20Management.md ...

**Comment by jgoldhammer** [comment]
Hi Bindu,

Thanks for the link to your generator. I am speaking about the standalone repo amp archetype, not the aio based projects. Your docs show how to add amps as overlay, or I am missing something here?

Thanks,
Jens

**Comment by binduwavell** [comment]
Jens,

Yes we assume AIO because that's the only archetype that should be used :) Unless you are doing something that is repo only or share only... but who would do that? :)

Yes it's overlay, but the alfresco-maven-plugin will actually use MMT to do that overlaying. Also there are docs on the other things that are required to get RAD stuff working with added modules.

-- Bindu

**Comment by gravitonian** [comment]
Hi,

What is the use-case exactly? Is it 1) that your repo-amp depends on other repo-amps to build? or 2) the project uses several repo customizations that you want to see when running with -Pamp-to-war? 
Also, do you have control, and source, for all AMPs?

If it is a dependency use-case, and you control the source, then I suggest you produce extra JAR artifacts with classes and config, see for example https://github.com/Alfresco/alfresco-sdk-samples/blob/new-samples-with-tests/all-in-one/repo-amp/pom.xml that uses the maven-jar-plugin to produce repo-amp-1.0-SNAPSHOT-classes.jar that can be dependent on by other projects, see https://github.com/Alfresco/alfresco-sdk-samples/blob/new-samples-with-tests/all-in-one/integration-test-runner/pom.xml for an example. 

If it is just a case of running alfresco.war with several repo customizations the you should use an AIO project.

We will be moving towards JAR artifacts in the future so these problems will be less frequent.
