### ISSUE TITLE
REST API calling from .NET client or alternative to trigger workflow from .NET application

### ISSUE THREAD

**Issue by Navaneeth22** [Alfresco/alfresco-sdk#379]
Hi,

I am able to get documents with CMIS library but not able to get any guide or the process to execute or trigger workflow on the document.

What are the possibilities to trigger alfresco workflow from .Net Application.

Presently, i am using community edition 5.1.

Regards,
Navaneeth

**Comment by ohej** [comment]
Hi

This question isn't really about the SDK - the SDK will help you build extensions to Alfresco not integrations.

You should be posting this question on the Alfresco forums - http://forums.alfresco.com.

CMIS does not offer any capabilities in terms of workflows, that's why we have the "v1" REST API's. They close the gab between what can be done via CMIS. You can find more information here: http://docs.alfresco.com/community/pra/1/topics/pra-welcome-aara.html - look for `Tasks`, `Processes` and `Process definitions`. A great tool to help you get an idea about the API's would be to use the REST API Explorer: https://api-explorer.alfresco.com/api-explorer/ - select "Workflow API" in the dropdown in the top right corner.

Again, as I wrote above, this question isn't related to the SDK so please post further questions in the forums. I'll close this issue.
