### ISSUE TITLE
New Alfresco SDK 2.2 allinone project does not transfer share client resources in amp/web folders

### ISSUE THREAD

**Issue by jgoldhammer** [Alfresco/alfresco-sdk#386]
Steps to reproduce

-  Create a new allinone project with SDK 2.2 and Java 1.8
-  Create a js file under src\main\amp\web\components\documentlibrary

![image](https://cloud.githubusercontent.com/assets/3872101/17437142/28fd21e0-5b1c-11e6-8720-3ef7eccf0f38.png)

-  Execute run.sh/run.bat in the root folder
![image](https://cloud.githubusercontent.com/assets/3872101/17437223/c7668ff6-5b1c-11e6-9069-6d21e80dda93.png)

- Sniffing into the amp file- the web folder is missing whereas the exploded amp folder contains the web folder...

![image](https://cloud.githubusercontent.com/assets/3872101/17437278/169da640-5b1d-11e6-8875-6ea20baa70d4.png)

**Comment by gravitonian** [comment]
This is by design to enable hot-reloading in SDK 2.x. See SDK 3 docs for more info: https://docs.google.com/document/d/1p5QR1Q8pVvMT9fh_aID5nraD5NP6ZrU1ztcgE_zHR-4/pub#h.fbko361frh31 

The `includeWebResources` property for the Alfresco Maven Plugin controls this.

To produce the correct AMP for distribution you need to use: `mvn clean install` 
(without the -Prun or -Pamp-to-war)

**Comment by jgoldhammer** [comment]
Thanks for clarification. I will close the ticket...
