### ISSUE TITLE
https://oss.sonatype.org/ does not contain SDK 3.0 Beta artifacts

### ISSUE THREAD

**Issue by lutzhorn** [Alfresco/alfresco-sdk#411]
https://www.alfresco.com/blogs/developer/2016/08/23/alfresco-sdk-3-beta-1-available/ advises to use https://oss.sonatype.org/content/repositories/orgalfresco-1039 in the `settings.xml`. This repository does not exist. In fact, https://oss.sonatype.org/ does not contain anything related to Alfresco.

What Maven repository shall be configured in the `settings.xml` to enable SDK 3.0 Beta?

**Comment by ohej** [comment]
I've had this issue raised with OSS Central and apparently the staging repositories we use to host the betas have a maximum lifetime of 7-14 days. Then we either have to release it or create a new staging repository.

We're working on getting the betas hosted on our internal Nexus, I expect we have this sorted out later today or tomorrow.

In the mean time, you can clone the SDK from Github, check out the `sdk-3.0` branch and do a `mvn clean install -Dmaven.test.skip=true".

Then you've successfully installed it locally and you can generate a new project using this command:
`mvn archetype:generate -DarchetypeCatalog=local"

Sorry for the inconvenience, I didn't realise the hard limit on the staging repositories until last week, I'll keep you posted (and update the blog post) as soon as we have news.

**Comment by lutzhorn** [comment]
Any update on this? Do we have an URL for a working repsitory?

**Comment by ohej** [comment]
Since Maven Central deletes the staging repositories we have changed our build setup for the SDK.

Releases are now done by default to our own repository (artifacts.alfresco.com) rather than Maven central.

The idea is that we now put all betas and release candidates on our own internal one - the final releases are put on Maven Central.

You can now access 3.0.0-beta-4 using this command:
`mvn archetype:generate -DarchetypeCatalog=https://artifacts.alfresco.com/nexus/content/groups/public/archetype-catalog.xml -Dfilter=org.alfresco.maven.archetype:`

Please make sure to use the full command.

@lutzhorn can you give it a spin and let me know if everything works as expected?

**Comment by lutzhorn** [comment]
Using `<alfresco.sdk.version>3.0.0-beta-4</alfresco.sdk.version>` works without an additional repository in the `settings.xml`.
