### ISSUE TITLE
Custom Platform & Share wars are being deployed to local repo SDK 3.0

### ISSUE THREAD

**Issue by shazada** [Alfresco/alfresco-sdk#448]
When you run a Alfresco SDK 3.0 project with alfresco:run command it deploys an overlayed war in your local Maven Repo.

[INFO] Deploying dependency wars
[INFO] Deploy warfile: D:\Program Files\apache-maven-3.0.4\repository\nl\contezza\addons\cntz-setup-console-platform\1.0.0\cntz-setup-console-platform-1.0.0.war to contextPath: /alfresco
[INFO] Deploy warfile: D:\Program Files\apache-maven-3.0.4\repository\org\alfresco\alfresco-solr4\5.2.e\alfresco-solr4-5.2.e.war to contextPath: /solr4
[INFO] Deploy warfile: D:\Program Files\apache-maven-3.0.4\repository\org\alfresco\api-explorer\5.2.e\api-explorer-5.2.e.war to contextPath: /api-explorer

In my current case cntz-setup-console-platform-1.0.0.war & cntz-setup-console-share-1.0.0.war.
So for every addon I create it will create a Full Platform & Share War and deploy that war in my local REPO.

So this is well over 200+MB for every module. These wars should be deployed in the target folder and not in the Maven Repo.

**Comment by ohej** [comment]
Thanks for the feedback. This is not much different than how we used to do it in previous releases - however this doesn't mean we don't want to change it.

The main reason this is done is for the tomcat plugin to be able to pick it up by GAV (groupId/artifactId/version). The tomcat plugin doesn't allow us to deploy multiple war projects without GAV. If we only had one WAR file to deploy it would be easier as we can unzip the file and set the location, however this isn't available when using `<webapps/>` along with the `run` goal of the tomcat plugin.

One way we might "cheat" the system is to point the GAV to a dummy artifact and then provide a context file which sets the doc path to the unzipped WAR file. It would also shave off some seconds on zipping and unzipping. 

The good news is however that since all of this is handled by the plugin, we could actually implement this change without requiring any changes to downstream projects, if we manage to crack it a simple bump in the version for the `alfresco-maven-plugin` could potentially be enough.

**Comment by ohej** [comment]
.... "close and comment" is too close to the "comment" button - or I have fat fingers :P Reopening

**Comment by shazada** [comment]
Great, yeah I didn't noticed this probably before :P. You are totally right that this was the case before as well :).
Enhancement is then a right label for this Thanks.

**Comment by shazada** [comment]
I guess you're right, I've done this with the old 2.2 SDK as I wanted to Run SOLR with REPO similar as how you're describing this:

```
<plugin>
						<groupId>org.apache.tomcat.maven</groupId>
						<artifactId>tomcat7-maven-plugin</artifactId>
						<configuration>
							<ignorePackaging>true</ignorePackaging>
							<!-- Make sure Catalina classes are picked up when we got virtual webapp contexts with classpaths -->
							<useSeparateTomcatClassLoader>true</useSeparateTomcatClassLoader>
							<path>/</path>
							<systemProperties>
								<alfresco.solr.home>${alfresco.solr.home.dir}</alfresco.solr.home>
							</systemProperties>
							<!-- Should this class loader delegate to the parent class loader before searching its own repositories (i.e. the usual Java2 delegation model) -->
							<!-- Prevent parent classloader delegation, each webapp loads. If set to true then you will get a truckload of Solr logging as the alf_data_dev/solr4/config/log4j-solr.properties file is not picked 
								up. This also fixes issues with the Google Guava Library, which this tomcat plugin uses version 10.0.1 of but Solr uses 14.0.1 -->
							<delegate>false</delegate>
							<webapps>
								<webapp>
									<groupId>${alfresco.groupId}</groupId>
									<artifactId>alfresco-solr4</artifactId>
									<version>${alfresco.version}</version>
									<type>war</type>
									<asWebapp>true</asWebapp>
									<contextPath>/solr4</contextPath>
									<contextFile>${alfresco.solr.home.dir}/context.xml</contextFile>
								</webapp>
							</webapps>
						</configuration>
					</plugin>
```

**Comment by ohej** [comment]
Exactly. If you look at the output from the Maven plugin you can actually see that it is generating a similar `<webapps>` section (it outputs the XML), so it's still doing the same thing, we just wrap around it in the Alfresco Maven Plugin. Again, I do see some potential workarounds for this, but needs some investigation.

**Comment by ohej** [comment]
For SDK 3.x I don't see a way to work around this issue. For SDK 4.x this will not be an issue anymore. Closing.
