### ISSUE TITLE
ClassNotFoundException running Integration Tests

### ISSUE THREAD

**Issue by ladenberger** [Alfresco/alfresco-sdk#455]
## I'm submitting a ...  
```
[x] bug report
[ ] feature request
```

## Expected Behavior

No ClassNotFoundException should be thrown at the end of running integration tests.

## Current Behavior

The following exceptions are thrown at the end of running integration tests: (see stack trace/log excerpt in "Additional information" section). Please also note that the build/goal is marked as "BUILD SUCCESS" and everything seems to be fine (i.e. the integration tests have been executed successfully).

## Possible Solution

A first idea is that the mentioned classes are not available in the classpath when stopping the embedded tomcat / end of build lifecycle.

## Steps to Reproduce (for bugs)

1. Create a new AIO Alfresco SDK 3 project.
2. Run "mvn verify" in the AIO project
3. Wait until the end
4. Check log messages

## Context

n/a

## Your Environment

* Alfresco SDK version used: 3.0 Release
* Alfresco version used: 5.2 Enterprise/Community
* Output of command 'mvn -version': Apache Maven 3.3.9

## Additional information

Stack Trace/Log excerpt:

```
[INFO] ------------------------------------------------------------------------

[INFO] Reactor Summary:

[INFO] 

[INFO] AIO - SDK 3.0 Beta ................................. SUCCESS [  0.864 s]

[INFO] Alfresco Platform/Repository JAR Module ............ SUCCESS [  9.461 s]

[INFO] Alfresco Share JAR Module .......................... SUCCESS [  0.659 s]

[INFO] Integration Tests Module ........................... SUCCESS [05:10 min]

[INFO] ------------------------------------------------------------------------

[INFO] BUILD SUCCESS

[INFO] ------------------------------------------------------------------------

[INFO] Total time: 05:22 min

[INFO] Finished at: 2017-04-19T14:46:04+02:00

[INFO] Final Memory: 375M/1828M

[INFO] ------------------------------------------------------------------------

java.lang.NoClassDefFoundError: de/schlichtherle/truezip/fs/FsLockController$1Sync
	at de.schlichtherle.truezip.fs.FsLockController.sync(FsLockController.java:240)
	at de.schlichtherle.truezip.fs.archive.zip.KeyController.sync(KeyController.java:128)
	at de.schlichtherle.truezip.fs.FsDecoratingController.sync(FsDecoratingController.java:131)
	at de.schlichtherle.truezip.fs.FsFalsePositiveArchiveController.sync(FsFalsePositiveArchiveController.java:480)
	at de.schlichtherle.truezip.fs.FsManager.sync(FsManager.java:105)
	at de.schlichtherle.truezip.fs.FsDefaultManager.sync(FsDefaultManager.java:190)
	at de.schlichtherle.truezip.fs.FsSyncShutdownHook$Hook.run(FsSyncShutdownHook.java:93)
Caused by: java.lang.ClassNotFoundException: de.schlichtherle.truezip.fs.FsLockController$1Sync
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 7 more
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
	at org.apache.tomcat.maven.plugin.tomcat7.run.RunMojo$1.run(RunMojo.java:140)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 1 more
ERROR: IllegalAccessException for stop method in class org.apache.tomcat.maven.plugin.tomcat7.run.ExtendedTomcat
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.maven.common.run.EmbeddedRegistry.shutdownAll(EmbeddedRegistry.java:110)
	at org.apache.tomcat.maven.common.run.EmbeddedRegistry$1.run(EmbeddedRegistry.java:69)
Caused by: org.apache.catalina.LifecycleException: Failed to stop component [StandardServer[-1]]
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:236)
	at org.apache.catalina.startup.Tomcat.stop(Tomcat.java:351)
	... 6 more
Caused by: org.apache.catalina.LifecycleException: Failed to stop component [StandardService[Tomcat]]
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:236)
	at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:753)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
	... 7 more
Caused by: org.apache.catalina.LifecycleException: Failed to stop component [StandardEngine[Tomcat]]
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:236)
	at org.apache.catalina.core.StandardService.stopInternal(StandardService.java:502)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
	... 9 more
Caused by: java.lang.NoClassDefFoundError: org/apache/catalina/core/ContainerBase$StopChild
	at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:1173)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
	... 11 more
Caused by: java.lang.ClassNotFoundException: org.apache.catalina.core.ContainerBase$StopChild
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 13 more
```

**Comment by eyaroslavtsev** [comment]
+1. I've the same thing.

**Comment by ccm73** [comment]
+1 - same thing (albeit with platform-jar-archetype).

**Comment by andrakula** [comment]
+1. I've the same thing.

**Comment by pavotm** [comment]
+1 same for me (platform-jar-archetype)

**Comment by M-Thirumal** [comment]
Same problem for me too

**Comment by M-Thirumal** [comment]
`[WARNING] Could not transfer metadata com.enkindle:indsolv-alfresco-platform-jar:1.0-SNAPSHOT/maven-metadata.xml from/to alfresco-private-repository (https://artifacts.alfresco.com/nexus/content/groups/private): Access denied to https://artifacts.alfresco.com/nexus/content/groups/private/com/enkindle/indsolv-alfresco-platform-jar/1.0-SNAPSHOT/maven-metadata.xml. Error code 401, Unauthorized
[WARNING] Failure to transfer com.enkindle:indsolv-alfresco-platform-jar:1.0-SNAPSHOT/maven-metadata.xml from https://artifacts.alfresco.com/nexus/content/groups/private was cached in the local repository, resolution will not be reattempted until the update interval of alfresco-private-repository has elapsed or updates are forced. Original error: Could not transfer metadata com.enkindle:indsolv-alfresco-platform-jar:1.0-SNAPSHOT/maven-metadata.xml from/to alfresco-private-repository (https://artifacts.alfresco.com/nexus/content/groups/private): Access denied to https://artifacts.alfresco.com/nexus/content/groups/private/com/enkindle/indsolv-alfresco-platform-jar/1.0-SNAPSHOT/maven-metadata.xml. Error code 401, Unauthorized
[INFO] Downloading: https://artifacts.alfresco.com/nexus/content/groups/private/com/enkindle/indsolv-alfresco-platform-jar/1.0-SNAPSHOT/indsolv-alfresco-platform-jar-1.0-SNAPSHOT.jar
[WARNING] The following dependencies could not be resolved at this point of the build but seem to be part of the reactor:
[WARNING] o com.enkindle:indsolv-alfresco-platform-jar:jar:1.0-SNAPSHOT (test)
[WARNING] Try running the build up to the lifecycle phase "package"
[INFO] 
[INFO] --- alfresco-maven-plugin:3.0.0:run (default-cli) @ indsolv-alfresco ---
[INFO] Unpacking Solr config
[INFO] Configured Artifact: org.alfresco:alfresco-solr4:config:5.2.e:zip
[INFO] alfresco-solr4-5.2.e-config.zip already unpacked.
[INFO] Fix Solr Home Path to work in Windows
[INFO] Replacing Solr config properties
[INFO] Replacement run on 2 files.
[INFO] Copying and filtering alfresco-global-*.properties files to target/test-classes
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] Replacement run on 7 files.
[INFO] Renaming alfresco-global-h2.properties to alfresco-global.properties
[INFO] Renamed C:\Users\Enkindle\git\indsolv-alfresco\target\test-classes\alfresco-global-h2.properties to C:\Users\Enkindle\git\indsolv-alfresco\target\test-classes\alfresco-global.properties
[INFO] Configured Artifact: org.alfresco:alfresco:5.2.e:war
[INFO] alfresco-5.2.e.war already unpacked.
[INFO] Configured Artifact: org.alfresco:alfresco-share-services:5.2.d:amp
[INFO] Copying alfresco-share-services-5.2.d.amp to C:\Users\Enkindle\git\indsolv-alfresco\target\modules\platform\amps\alfresco-share-services-5.2.d.amp
[info] Installing all AMPs from directory C:\Users\Enkindle\git\indsolv-alfresco\target\modules\platform\amps into WAR/exploded webapp at C:\Users\Enkindle\git\indsolv-alfresco\target\platform-war
[info] AMPs installed successfully
[INFO] Configured Artifact: com.enkindle:indsolv-alfresco-platform-jar:1.0-SNAPSHOT:jar
[WARNING] Failure to transfer com.enkindle:indsolv-alfresco-platform-jar:1.0-SNAPSHOT/maven-metadata.xml from https://artifacts.alfresco.com/nexus/content/groups/private was cached in the local repository, resolution will not be reattempted until the update interval of alfresco-private-repository has elapsed or updates are forced. Original error: Could not transfer metadata com.enkindle:indsolv-alfresco-platform-jar:1.0-SNAPSHOT/maven-metadata.xml from/to alfresco-private-repository (https://artifacts.alfresco.com/nexus/content/groups/private): Access denied to https://artifacts.alfresco.com/nexus/content/groups/private/com/enkindle/indsolv-alfresco-platform-jar/1.0-SNAPSHOT/maven-metadata.xml. Error code 401, Unauthorized
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] AIO - SDK 3.0 Beta ................................. FAILURE [  9.041 s]
[INFO] Alfresco Platform/Repository JAR Module ............ SKIPPED
[INFO] Alfresco Share JAR Module .......................... SKIPPED
[INFO] Integration Tests Module ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.570 s
[INFO] Finished at: 2017-05-19T14:32:35+05:30
[INFO] Final Memory: 33M/271M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.alfresco.maven.plugin:alfresco-maven-plugin:3.0.0:run (default-cli) on project indsolv-alfresco: Unable to execute mojo: Unable to resolve artifact. Failure to transfer com.enkindle:indsolv-alfresco-platform-jar:jar:1.0-SNAPSHOT from https://artifacts.alfresco.com/nexus/content/groups/private was cached in the local repository, resolution will not be reattempted until the update interval of alfresco-private-repository has elapsed or updates are forced. Original error: Could not transfer artifact com.enkindle:indsolv-alfresco-platform-jar:jar:1.0-SNAPSHOT from/to alfresco-private-repository (https://artifacts.alfresco.com/nexus/content/groups/private): Access denied to https://artifacts.alfresco.com/nexus/content/groups/private/com/enkindle/indsolv-alfresco-platform-jar/1.0-SNAPSHOT/indsolv-alfresco-platform-jar-1.0-SNAPSHOT.jar. Error code 401, Unauthorized
[ERROR] com.enkindle:indsolv-alfresco-platform-jar:jar:1.0-SNAPSHOT
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR] alfresco-public (https://artifacts.alfresco.com/nexus/content/groups/public, releases=true, snapshots=true),
[ERROR] alfresco-public-snapshots (https://artifacts.alfresco.com/nexus/content/groups/public-snapshots, releases=true, snapshots=true),
[ERROR] alfresco-private-repository (https://artifacts.alfresco.com/nexus/content/groups/private, releases=true, snapshots=true),
[ERROR] central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
java.lang.NoClassDefFoundError: de/schlichtherle/truezip/fs/FsLockController$1Sync
	at de.schlichtherle.truezip.fs.FsLockController.sync(FsLockController.java:240)
	at de.schlichtherle.truezip.fs.archive.zip.KeyController.sync(KeyController.java:128)
	at de.schlichtherle.truezip.fs.FsDecoratingController.sync(FsDecoratingController.java:131)
	at de.schlichtherle.truezip.fs.FsFalsePositiveArchiveController.sync(FsFalsePositiveArchiveController.java:480)
	at de.schlichtherle.truezip.fs.FsManager.sync(FsManager.java:105)
	at de.schlichtherle.truezip.fs.FsDefaultManager.sync(FsDefaultManager.java:190)
	at de.schlichtherle.truezip.fs.FsSyncShutdownHook$Hook.run(FsSyncShutdownHook.java:93)
Caused by: java.lang.ClassNotFoundException: de.schlichtherle.truezip.fs.FsLockController$1Sync
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 7 more
`

**Comment by bmlong137** [comment]
I had the same problem.  But then I found the issue.  The problem with this error is that it is incredibly deceptive.  In my situation, because it couldn't find the AMP specified in the alfresco-maven-plugin shareModules configuration element, it output the error in this thread.  I am working with classifiers, so I had to specify the classifier and then the error went away.

So make sure this is not an issue where the JAR or AMP you are including does not exist...at least per the platformModules and shareModules XML elements in the alfresco-maven-plugin configuration.

**Comment by p4535992** [comment]
Same problem for me too,  anyone have found the solution?

**Comment by uvukasinovic** [comment]
+1 - same problem (platform-jar-archetype)

**Comment by ilyagalahov** [comment]
+1

**Comment by sorin-postelnicu** [comment]
I am having the same problem, and it's with an empty getting-started sample.
The SDK 3.0 is NOT working out-of-the-box.

**Comment by trycoon** [comment]
+1

**Comment by LukasKraushofer** [comment]
+1

**Comment by schocco** [comment]
I am observing the same behaviour with SDK 3.0.1. I experimented with changes in the type declaration as bmlong137 mentioned, but had no success with it.

**Comment by erwin314** [comment]
I'm also observing the same problem with SDK 3.0.1.

**Comment by deas** [comment]
Those issues are related to shutdown hooks in various places (at least one in tomcat iirc). They don't play nice with maven plugin lifecyle and classloading. As far as I known, they don't cause any issues other than ugly stacktrace output. Hence, I would not expect this issue to be fixed anytime soon.

**Comment by erwin314** [comment]
I can confirm that it is related to the JVM shutdown hooks not playing nicely with the maven lifecycle and classloading. 

When I remove all shutdown hooks the exception messages are no longer displayed. :thumbsup:

This was tested by removing the shutdown hooks before the tests end. Removing those hooks is a bit of a hack:

```java
private void removeShutdownHooks() throws ReflectiveOperationException {
    @SuppressWarnings("rawtypes")
    Class clazz = Class.forName("java.lang.ApplicationShutdownHooks");
    Field field = clazz.getDeclaredField("hooks");
    field.setAccessible(true);

    @SuppressWarnings("unchecked")
    Map<Thread, Thread> hooks = (Map<Thread, Thread>)field.get(null);
    hooks.clear();
}
```

**Comment by DEEPAK-KESWANI** [comment]
> ## I'm submitting a ...
> ```
> [x] bug report
> [ ] feature request
> ```
> ## Expected Behavior
> No ClassNotFoundException should be thrown at the end of running integration tests.
> 
> ## Current Behavior
> The following exceptions are thrown at the end of running integration tests: (see stack trace/log excerpt in "Additional information" section). Please also note that the build/goal is marked as "BUILD SUCCESS" and everything seems to be fine (i.e. the integration tests have been executed successfully).
> 
> ## Possible Solution
> A first idea is that the mentioned classes are not available in the classpath when stopping the embedded tomcat / end of build lifecycle.
> 
> ## Steps to Reproduce (for bugs)
> 1. Create a new AIO Alfresco SDK 3 project.
> 2. Run "mvn verify" in the AIO project
> 3. Wait until the end
> 4. Check log messages
> 
> ## Context
> n/a
> 
> ## Your Environment
> * Alfresco SDK version used: 3.0 Release
> * Alfresco version used: 5.2 Enterprise/Community
> * Output of command 'mvn -version': Apache Maven 3.3.9
> 
> ## Additional information
> Stack Trace/Log excerpt:
> 
> ```
> [INFO] ------------------------------------------------------------------------
> 
> [INFO] Reactor Summary:
> 
> [INFO] 
> 
> [INFO] AIO - SDK 3.0 Beta ................................. SUCCESS [  0.864 s]
> 
> [INFO] Alfresco Platform/Repository JAR Module ............ SUCCESS [  9.461 s]
> 
> [INFO] Alfresco Share JAR Module .......................... SUCCESS [  0.659 s]
> 
> [INFO] Integration Tests Module ........................... SUCCESS [05:10 min]
> 
> [INFO] ------------------------------------------------------------------------
> 
> [INFO] BUILD SUCCESS
> 
> [INFO] ------------------------------------------------------------------------
> 
> [INFO] Total time: 05:22 min
> 
> [INFO] Finished at: 2017-04-19T14:46:04+02:00
> 
> [INFO] Final Memory: 375M/1828M
> 
> [INFO] ------------------------------------------------------------------------
> 
> java.lang.NoClassDefFoundError: de/schlichtherle/truezip/fs/FsLockController$1Sync
> 	at de.schlichtherle.truezip.fs.FsLockController.sync(FsLockController.java:240)
> 	at de.schlichtherle.truezip.fs.archive.zip.KeyController.sync(KeyController.java:128)
> 	at de.schlichtherle.truezip.fs.FsDecoratingController.sync(FsDecoratingController.java:131)
> 	at de.schlichtherle.truezip.fs.FsFalsePositiveArchiveController.sync(FsFalsePositiveArchiveController.java:480)
> 	at de.schlichtherle.truezip.fs.FsManager.sync(FsManager.java:105)
> 	at de.schlichtherle.truezip.fs.FsDefaultManager.sync(FsDefaultManager.java:190)
> 	at de.schlichtherle.truezip.fs.FsSyncShutdownHook$Hook.run(FsSyncShutdownHook.java:93)
> Caused by: java.lang.ClassNotFoundException: de.schlichtherle.truezip.fs.FsLockController$1Sync
> 	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
> 	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
> 	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
> 	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
> 	... 7 more
> Exception in thread "Thread-4" java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
> 	at org.apache.tomcat.maven.plugin.tomcat7.run.RunMojo$1.run(RunMojo.java:140)
> Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
> 	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
> 	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
> 	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
> 	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
> 	... 1 more
> ERROR: IllegalAccessException for stop method in class org.apache.tomcat.maven.plugin.tomcat7.run.ExtendedTomcat
> java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.tomcat.maven.common.run.EmbeddedRegistry.shutdownAll(EmbeddedRegistry.java:110)
> 	at org.apache.tomcat.maven.common.run.EmbeddedRegistry$1.run(EmbeddedRegistry.java:69)
> Caused by: org.apache.catalina.LifecycleException: Failed to stop component [StandardServer[-1]]
> 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:236)
> 	at org.apache.catalina.startup.Tomcat.stop(Tomcat.java:351)
> 	... 6 more
> Caused by: org.apache.catalina.LifecycleException: Failed to stop component [StandardService[Tomcat]]
> 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:236)
> 	at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:753)
> 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
> 	... 7 more
> Caused by: org.apache.catalina.LifecycleException: Failed to stop component [StandardEngine[Tomcat]]
> 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:236)
> 	at org.apache.catalina.core.StandardService.stopInternal(StandardService.java:502)
> 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
> 	... 9 more
> Caused by: java.lang.NoClassDefFoundError: org/apache/catalina/core/ContainerBase$StopChild
> 	at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:1173)
> 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
> 	... 11 more
> Caused by: java.lang.ClassNotFoundException: org.apache.catalina.core.ContainerBase$StopChild
> 	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
> 	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
> 	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
> 	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
> 	... 13 more
> ```

The below command solved my problem
`mvn dependency:resolve`
