### ISSUE TITLE
Spring-context dependency missing at compile time

### ISSUE THREAD

**Issue by ohej** [Alfresco/alfresco-sdk#470]
## I'm submitting a ...   (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

When trying to develop a patch with SDK 3.0 a compilation error is thrown during maven compilation phase due to lack of a dependency to spring-context. 

See https://issues.alfresco.com/jira/browse/ALF-21899 for more info.

**Comment by igorbga** [comment]
I have just had a similar issue trying to use apache-commons-csv. By default this is not included by the SDK although this is a "jar" already provided by Alfresco.

I know you are already thinking about what to do with all the dependencies that Alfresco already provides so I thought I would just add my two cents just in case another opinion is helpful.

Adding the dependency to the pom is not a big deal for a developer if it is documented that this is the right way to go. You add the dependency to the pom with the same version as your Alfresco versions's jar and set the scope to "provided" and that's it. 

The real problem is that by adding an specific version you must be very careful whenever you decide to update your Alfresco version and the idea of just having to add a couple of properties in the pom vanishes, if you have several provided Alfresco dependencies added by hand you have to recheck all of them.

So I would suggest that the SDK should try to act at the dependency management level. Maybe a pom artifact can be created with all the dependencyManagement section for this particular version and the archetype might just have a dependency to the corresponding artifact. Does it make any sense? Not sure if this is really posible but sounds an option to try.
