### ISSUE TITLE
Hotswap share not working

### ISSUE THREAD

**Issue by kodermax** [Alfresco/alfresco-sdk#487]
## I'm submitting a ...   (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```
Refresh webscripts on the path src/main/resources/META-INF/resources/components/upload/dnd-upload-custom.js
with goal ```mvn compile alfresco:refresh-share``` does refresh but the changes aren't visible.

## Your Environment
<alfresco.sdk.version>3.0.1</alfresco.sdk.version>
<alfresco.platform.version>5.2.f</alfresco.platform.version>
<alfresco.share.version>5.2.e</alfresco.share.version>

**Comment by binduwavell** [comment]
@kodermax, I don’t think hotseap is involved with JS WebScript reloading. I wonder if you might want to place your WebScript in the extension-web path?

**Comment by gehriga** [comment]
Hi @binduwavell ,
I've encountered the same problem. The mentioned file or path ain't a Webscript JS, but a client-side file.
src/main/resources/META-INF/resources is the correct path for placing such a file, especially when you're producing a JAR module and not an AMP.

I've tried several hours to make Share reload changes there, but without success. Neither through "refresh webscripts", setting "disable-resource-caching" in share-config-custom.xml to true, nor through HotSwapAgent's capabilities.

I think this has to be addressed by the SDK. Especially because it has been possible with older versions of the SDK (where those files were part of the AMP, which (I think) was the reason for this to work).

**Comment by Mord1n** [comment]
Im having the same issue as gehriga, any solutions or workarounds would be greatly appreciated.

**Comment by MatsKarlsson** [comment]
Think it's the same as with repo. As a workaround I have gotten it to work using HotSwapAgent following: https://docs.alfresco.com/5.2/tasks/sdk-hot-reload-hotswap.html

For me it works with web scripts and java code in repo.

**Comment by dvps-ad** [comment]
Hi @gehriga @binduwavell,

Same thing for me, with SDK 3.0.1, Alfresco 5.2.1.

The resources (JS) are in src/main/resources/META-INF/resources (trying in web folder with the same result), disable-resource-caching is true. mvn compile alfresco:refresh-share does not work with and without HotSwapAgent.

Any news from your side ?
